### ISSUE TITLE
Filter throw unorderable type error

### ISSUE THREAD

**Issue by fschloesser** [GregorCH/ipet#24]
This happens when a filter is referring to a column that has been discharded earlier, i.e. an original column that is not being used in the columns. Then the filter treats the columname as string and can't compare it to any values.
Is this behaviour intended?

**Comment by GregorCH** [comment]
No, that is an issue. Just like columns, filters should communicate the columns that they need to the evaluation, such that all necessary columns are present when the filter is invoked.

**Comment by GregorCH** [comment]
Can you create a minimal working example how you discovered it?

**Comment by fschloesser** [comment]
Run the miplip benchmark logfiles with this eval-file:

<?xml version="1.0" ?>
<Evaluation defaultgroup="SCIP" index="ProblemName Solver" indexsplit="1">
	<Column active="True" origcolname="Status" reduction="meanOrConcat" />
	<FilterGroup filtertype="intersection" name="all">
		<Filter anytestrun="one" expression1="SolvingTime" expression2="10" operator="ge"/>
	</FilterGroup>
</Evaluation>

**Comment by GregorCH** [comment]
Which eval-file?
