### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by fschloesser** [GregorCH/ipet#36]
Especially for ipet-evaluate, there should be tests against mistakes in userinput.

**Comment by GregorCH** [comment]
Can you be more specific what needs testing? This issue is rather vague.

**Comment by fschloesser** [comment]
I've wanted this to be here without thinking about it that much. Yes, it needs to be specified better, I guess at least we should check the following:

- for each attribute that the user can edit in xml we should check for 

-- existing but nonsensical values
-- nonexisting values / typos
-- not specifying the attribute/value pair at all resp. missing, but required, pairs 
-- misformatted index/defaultgroup

- broken xml code
- (maybe) special things we assume, e.g. circular dependencies

**Comment by GregorCH** [comment]
I think there are two levels of testing mentioned that  can be treated individually:
- XML parsing, making sure that the string input is set correctly
- behavior of the objects during the evaluation

**Comment by GregorCH** [comment]
I will close this issue because it is not constructive. We both take care during development that necessary tests are added together with the code.
