### ISSUE TITLE
PrimalHistory few elements

### ISSUE THREAD

**Issue by leoneifler** [GregorCH/ipet#37]
Test instance takes only one primal value at root node, resulting in a very large primal integral. 
[debug-spa.out.txt](https://github.com/GregorCH/ipet/files/1189914/debug-spa.out.txt)

**Comment by leoneifler** [comment]
The problem is the empty line after the first heuristic solution. I don't know why scip does this, but if I remove it manually then ipet does the primalHistory correctly

**Comment by leoneifler** [comment]
The empty line is a mistake on my part. Is it still desirable that ipet can handle empty lines in the input or should I just close this issue?

**Comment by GregorCH** [comment]
No, you are right, it is desirable. I will take care of this.

**Comment by GregorCH** [comment]
This is fixed with pull request #41
