### ISSUE TITLE
DualBoundHistory not read for gurobi output

### ISSUE THREAD

**Issue by leoneifler** [GregorCH/ipet#38]
When parsing a *.out file from a gurobi-run, dual bound history is empty.

[debug_gurobi.out.txt](https://github.com/GregorCH/ipet/files/1189943/debug_gurobi.out.txt)

**Comment by GregorCH** [comment]
The dual bound history, so far, has been exclusively written for SCIP. If you want, @leoneifler , you can try to implement this yourself in the GurobiSolver class in ipet/parsing/Solver.py

**Comment by leoneifler** [comment]
Ok I will try to do that

**Comment by GregorCH** [comment]
Just make yourself familiar with how the SCIPSolver does it, and try to figure out the Gurobi peculiarities. If you happen to know a better parsing library to simplify that task, I am open to include this into IPET.
Make sure that you use the Key module for providing the data key "DualBoundHistory".

If you have questions, post them here.

**Comment by leoneifler** [comment]
Ok that was easy, I just adapted how it works for gurobi primal history. Shall/Can I just push this to master or do you want me to create a new branch and merge that later?

**Comment by GregorCH** [comment]
The workflow here on github foresees that you
1. create a fork of ipet
2. create an experimental branch with the code changes in your fork
3. create a pull request from your fork into ipet
